name: Comprehensive Setup and Deployment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create CI/CD User
        run: |
          sudo adduser --disabled-password --gecos 'CI/CD User' ci-cd-user || echo "User already exists"
          echo "CI/CD User created or already exists"

      - name: Update System
        run: |
          sudo dnf update
          sudo dnf upgrade -y

      - name: Install Docker and Git
        run: |
          sudo dnf install -y docker.io git

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone Spring Petclinic Project
        run: |
          git clone https://github.com/spring-projects/spring-petclinic.git

      - name: Build Pilot Project
        run: |
          cd spring-petclinic
          ./mvnw package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          cd spring-petclinic
          docker build -t spring-petclinic .

      - name: Run Docker Container
        run: |
          docker run -d -p 8090:8080 spring-petclinic

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Verify Pilot Project URL
        run: |
          curl -I http://localhost:8090
