name: Spring PetClinic CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        if ! command -v docker &> /dev/null
        then
          echo "Docker not found, installing..."
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
        else
          echo "Docker already installed, skipping installation."
        fi

    - name: Install Docker Compose
      run: |
        if ! command -v docker-compose &> /dev/null
        then
          echo "Docker Compose not found, installing..."
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        else
          echo "Docker Compose already installed, skipping installation."
        fi

    - name: Start PostgreSQL and MySQL containers
      run: docker-compose up -d

  build:
    needs: setup-environment
    strategy:
      matrix:
        vm: [103.151.111.190, 103.151.111.241, 103.151.111.188]
    runs-on: self-hosted

    steps:
    - name: Run on VM
      run: |
        ssh ${{ matrix.vm }} 'cd /path/to/project && ./mvnw clean install'

  deploy:
    needs: build
    strategy:
      matrix:
        vm: [103.151.111.190, 103.151.111.241, 103.151.111.188]
    runs-on: self-hosted

    steps:
    - name: Deploy to VM
      run: |
        ssh ${{ matrix.vm }} 'cd /path/to/project && nohup java -jar target/*.jar --server.port=8090 &'

  test:
    needs: deploy
    runs-on: self-hosted

    steps:
    - name: Run Tests
      run: ./mvnw test
