name: Comprehensive Setup and Deployment

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create CI/CD User
        run: |
          if ! id -u ci-cd-user > /dev/null 2>&1; then
            sudo adduser --disabled-password --gecos 'CI/CD User' ci-cd-user
            echo "CI/CD User created."
          else
            echo "CI/CD User already exists."
          fi

      - name: Update System
        run: |
          sudo dnf update -y
          sudo dnf upgrade -y

      - name: Install Docker and Git
        run: |
          # Clean up DNF cache
          sudo dnf clean all
          sudo rm -rf /var/cache/dnf

          # Check and install Docker if not present
          if ! command -v docker &> /dev/null; then
            echo "Docker not found, installing..."
            sudo dnf install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker is already installed."
          fi

          # Check and install Git if not present
          if ! command -v git &> /dev/null; then
            echo "Git not found, installing..."
            sudo dnf install -y git
          else
            echo "Git is already installed."
          fi

  build:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Clone Spring Petclinic Project
        run: |
          if [ ! -d "spring-petclinic" ]; then
            git clone https://github.com/spring-projects/spring-petclinic.git
          else
            echo "Spring Petclinic project already cloned."
          fi

      - name: Build Pilot Project
        run: |
          cd spring-petclinic
          ./mvnw package

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: |
          cd spring-petclinic
          if ! docker image ls | grep -q spring-petclinic; then
            docker build -t spring-petclinic .
          else
            echo "Docker image 'spring-petclinic' already built."
          fi

      - name: Run Docker Container
        run: |
          if [ "$(docker ps -q -f name=spring-petclinic)" ]; then
            echo "Container 'spring-petclinic' is already running."
          else
            docker run -d --name spring-petclinic -p 8090:8080 spring-petclinic
          fi

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Verify Pilot Project URL
        run: |
          curl -I http://localhost:8090
